#!/lustre/scratch113/teams/zeggini/users/ds26/anaconda2/bin/python

'''
importing libraries that are independent from other functions.
This first block don't have to be executed each time:
'''

# library for simple web queries:
import requests, sys

# libray for parsing htlm files:
from lxml import html

# library for generate python data structure from string:
import ast

# Library to execute shell commands:
import subprocess

# Importing date library:
import datetime

# LIbrary for importing options:
import argparse

# Importing the templating library that creates html files:
egg_path='/nfs/users/nfs_d/ds26/local/lib/python2.7/site-packages/Django-1.8.6-py2.7.egg'
sys.path.append(egg_path)

# Load the jinja library's namespace into the current module.
import jinja2

# Reading saved functions:
from variations import *
from variations_draw import *
from genes import *
from genes_draw import *

# Generating footer string:
i = datetime.datetime.now()
date_string = i.strftime('%Y/%m/%d %H:%M:%S')

# Version:
version = "2.1.0"

# List of global variables (they are made global to make it easier to maintain)
# global GWAVA_dir,

# Parsing command line arguments:
parser = argparse.ArgumentParser()
input_options = parser.add_argument_group('Input options')
input_options.add_argument("-i", "--input", help="Input variation required: rsID or SNP ID + alleles: \"chr14:94844947_C/T\"", required=True)
input_options.add_argument("-g", "--GWAVA", help="Use this switch to perform GWAVA prediction of the queried variation.", required=False, action='store_true')

# Extracting command line parameters:
args = parser.parse_args()
SNP_ID = args.input
GWAVA = args.GWAVA

# Let's assume we have an rsID given by the user:
filename = SNP_ID.replace(" ", "_").replace("/", "_").replace(":","_")+".html"

# Submit for retrieving variant information:
print >> sys.stderr, "[Info] Retrieving variant data from Ensembl... ",
(population_data, variant_data) = get_rsID(SNP_ID)
print >> sys.stderr, "Done."

# Calculating GWAVA score only if the user wanted to:
if GWAVA:
    print >> sys.stderr, "[Info] Calculating GWAVA score of the variation...",
    variant_data = get_GWAVA_score(variant_data)
    print >> sys.stderr, "Done."

# Retrieving variations gwas signals in the close vicinity:
print >> sys.stderr, "[Info] Finding local GWAS hits around variation... ",
gwas_hits = get_gwas_hits_position(variant_data)
print >> sys.stderr,"Done."

# Retrieve VEP data:
print >> sys.stderr, "[Info] Calculating consequences for all overlapping transcripts... ",
(VEP_data, variant_data) = get_VEP_data(variant_data)
print >> sys.stderr, "Done."

# Retrieving pubmed ID-s:
print >> sys.stderr, "[Info] Retrieving list of publications from Pubmed... ",
pubmed_ids = get_pubmedIDs(variant_data["rsID"])
print >> sys.stderr, "Done."

# Return phenotypes:
print >> sys.stderr, "[Info] Returning variants with phenotype annotation... ",
phenotype_df = get_phenotype_vars({"chr" : variant_data["chromosome"],
               "start" : variant_data["start"] - config.WINDOW,
               "end" : variant_data["start"] + config.WINDOW,
               "var" : variant_data["start"] })
print >> sys.stderr, "Done."

# Get a list of genes close to the variation:
print >> sys.stderr, "[Info] Retrieving variant data from Ensembl... ",
gene_list = get_gene_list(variant_data)
print >> sys.stderr, "Done."

# Get population data from the Exome Aggregation Consortium:
print >> sys.stderr,"[Info] Retrieving minor allele frequencies from the Exome Aggregation Consortium data... ",
Exac_parsed = get_ExAC_frequencies(variant_data)
print >> sys.stderr, "Done."

# Checking variation in the GTEx database:
print >> sys.stderr,"[Info] Checking variation in the GTEx database... ",
GTEx_genes = get_GTEx_genes(variant_data)
print >> sys.stderr, "Done."

# Get population data from the Exome Aggregation Consortium:
print >> sys.stderr,"[Info] Retrieving allele frequencies from UK10K data... ",
ukData = get_UK10K_frequencies(variant_data)
print >> sys.stderr, "Done."

# Get regulatory features:
print >> sys.stderr,"[Info] Retrieving overlapping regulatory features from Ensembl... ",
regulation = get_regulation(variant_data)
print >> sys.stderr, "Done."

# Drawing tables for the output:
print >> sys.stderr, "[Info] Formatting retrieved information... ",
variant_table = draw_variation_table(variant_data)
regulatory_table = draw_regulation(regulation)
gwas_table = draw_gwas_position_table(gwas_hits)
VEP_table = draw_consequence_table(VEP_data)
population_table = draw_freq_table(population_data, variant_data["allele_string"])
pubmed_table = draw_pubmed_table(pubmed_ids)
uk10K_table = draw_UK10K_table(ukData)
gene_table = draw_gene_table(gene_list, SNP_ID.replace(" ", "_").replace("/", "_"))
exac_table = draw_ExAC_table(Exac_parsed, variant_data["reference"])
GTEx_genes_table = draw_GTEx_eQTL_table(GTEx_genes)
phenotype_table = draw_phenotpye_table_var(phenotype_df)
footer = "Generated by VarAnnoTool v.%s on: %s" %(version, date_string)
print >> sys.stderr, "Done."

# now we create the html string based on the template file and teh retrieved data:
print >> sys.stderr, "[Info] Saving data... ",
variation_template = config.VAR_TEMPLATE
variation_dict = { "variation_table" : variant_table.decode('utf-8'),
                 "footer" : footer.decode('utf-8'),
                 "gwas_table": gwas_table.decode('utf-8'),
                 "consequence_table": VEP_table.decode('utf-8'),
                 "regulation" : regulatory_table.decode('utf-8'),
                 "Genomes_freq" : population_table.decode('utf-8'),
                 "ExAC_freq" : exac_table.decode('utf-8'),
                 "UK10K_freq" : uk10K_table.decode('utf-8'),
                 "genes" : gene_table.decode('utf-8'),
                 'GTExGenes' : GTEx_genes_table.decode('utf-8'),
                 "pubmed" : pubmed_table.decode('utf-8'),
                 "phenotypes" : phenotype_table.decode('utf-8')}

html = draw_html(variation_template, variation_dict)

# Saving file:
f = open(filename, 'w')
f.write(html.encode("utf8"))

print >> sys.stderr, "Done."

print >> sys.stderr, "Annotating genes... "
for dist in gene_list.keys():
    for gene in gene_list[dist]:
        print >> sys.stderr, "\tAnnotating %s... " % gene["ID"],
        Annotate_gene(gene["ID"])
        print >> sys.stderr, "Done."
